---
title: "DE_16"
author: "Sam Remmey"
date: "2025-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(dplyr)

gene <- data.frame(readxl::read_excel("gene_count_16.xls"))
```


### Running DE on all 16 samples:
```{r}
counts_matrix <- gene[,1:17]
rownames(counts_matrix) <- counts_matrix$gene_id
counts_matrix <- counts_matrix %>%
  select(-gene_id)
counts_matrix <- as.matrix(counts_matrix)  # Convert to numeric


samples <- c("OS0658","OS21014","OD21014","AD22","AD24","AD25","RNA35","RNA41","RNA45","RNA47","RNA48","RNA53","RNA62","RNA44","RNA54","RNA61")
label <- c('CTRL','CTRL','CTRL','POAG','POAG','POAG','POAG','POAG','POAG','POAG','POAG','POAG','POAG','POAG','NTG','NTG')
labels <- data.frame(samples, label)
rownames(labels) <- labels$samples
labels <- labels %>%
  select(-samples)
```

```{r}
## Create a DESeqDataSet object
dds <- DESeqDataSetFromMatrix(countData = counts_matrix,
                              colData = labels,
                              design = ~ label)  # 'condition' should be a column in sample_info

# Filter low-count genes (optional)
#dds <- dds[rowSums(counts(dds)) > 10, ]

## Run DESeq analysis
dds <- DESeq(dds)
res <- results(dds)
```

```{r}
# p values
res <- res[order(res$padj), ]
head(res)

# Filter for Significant DEGs (Adjusted p-value < 0.05, Log2FC > 1)
sig_genes <- subset(res, padj < 0.05 & abs(log2FoldChange) > 1)
```

```{r}
# volcano plot
ggplot(as.data.frame(res), aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(alpha = 0.5) +
  geom_point(data = sig_genes, aes(x = log2FoldChange, y = -log10(padj)), color = "red") +
  theme_minimal() +
  xlab("Log2 Fold Change") +
  ylab("-Log10 Adjusted P-Value") +
  ggtitle("Volcano Plot of Differentially Expressed Genes")
```

```{r}
# Heatmap of Top Genes
top_genes <- rownames(sig_genes)[1:50]  # Select top 50 genes
normalized_counts <- counts(dds, normalized = TRUE)
pheatmap(normalized_counts[top_genes, ])
```








