---
title: "DE_6"
author: "James Siegener"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
gene_6 <- readxl::read_excel("gene_count_6.xls")
```

```{r}
#install.packages("BiocManager")  # If not already installed
#BiocManager::install("DESeq2")

library(DESeq2)
library(ggplot2)
library(tidyverse)
library(pheatmap)
```

```{r}
counts_6 <- gene_6 %>% select(gene_id, OS0658, OS21014, OD21014, AD22, RNA35, RNA62)

counts_6 <- counts_6 %>% column_to_rownames(var = "gene_id")

counts_6 <- as.matrix(counts_6)

mode(counts_6) <- "numeric"

sample_info_6 <- data.frame(
    row.names = colnames(counts),   # Sample names
    condition = c("control", "control", "control", "glaucoma", "glaucoma", "glaucoma")  # Group labels
)

sample_info_6$condition <- factor(sample_info_6$condition, levels = c("control", "glaucoma"))

```


```{r}

dds_6 <- DESeqDataSetFromMatrix(countData = counts_6,
                              colData = sample_info_6,
                              design = ~ condition)

# Filter out low-expression genes
# dds_6 <- dds_6[rowSums(counts_6(dds_6)) > 10, ]

# Run DESeq2 normalization and differential expression analysis
dds_6 <- DESeq(dds_6)

# Extract results (glaucoma vs. control)
res_6 <- results(dds_6, contrast = c("condition", "glaucoma", "control"))

# View summary
summary(res_6)

```
```{r}
sig_genes_6 <- subset(res_6, padj < 0.05 & abs(log2FoldChange) > 1)
```

```{r}
sig_genes_6
```

```{r}
head(res_6)
```

```{r}
res_df_6 <- as.data.frame(res_6) %>%
  rownames_to_column(var = "gene") %>%   
  drop_na()  

res_df_6$log2FoldChange <- as.numeric(res_df_6$log2FoldChange)
res_df_6$padj <- as.numeric(res_df_6$padj)

ggplot(res_df_6, aes(x = log2FoldChange, y = -log10(padj), color = padj < 0.05)) +
  geom_point(alpha = 0.6) +
  scale_color_manual(values = c("black", "red")) +  # Red for significant genes
  theme_minimal() +
  labs(title = "Volcano Plot", x = "Log2 Fold Change", y = "-Log10 Adjusted P-value")


```
```{r}
# Extract normalized counts
vsd_6 <- vst(dds_6, blind = FALSE)
top_genes_6 <- rownames(sig_genes_6)[1:25]

pheatmap(assay(vsd_6)[top_genes_6, ], cluster_rows = TRUE, cluster_cols = TRUE)


```
```{r}
top_genes_6

```
```{r}
plotPCA(vsd_6, intgroup = "condition") +
  theme_minimal() +
  ggtitle("PCA of RNA-seq Data")

```

```{r}

overlap <- intersect(top_genes_6, top_genes_16)
overlap

```
The gene that overlaps between running the analysis on all 16 genes and on just the 6 that are uncontaminated is gene ENSG00000104635. This gene is differentially expressed in both analyses. 
```{r}
res_6['ENSG00000104635',]

```
This gene seems to be strongly downregulated in glaucoma patients in both the 6 sample and 16 sample dataset. 


